In [27]:
import pandas as pd
import nbformat
import plotly.express as px
import kaleido
import psycopg2
from sqlalchemy import create_engine

In [28]:
df = pd.read_csv(r"C:\Users\gaurav giri\Desktop\archive (2)\Delhi Air Quality Time Series Dataset(01-01-2025 to 15-05-2026).csv")
df.head()

              DateTime  Locations Parameters  Values Units  hour
0  2025-02-18 20:00:00  R K Puram         no    93.2   ppb    20
1  2025-02-18 20:15:00  R K Puram         no    90.4   ppb    20
2  2025-02-18 21:00:00  R K Puram         no    84.7   ppb    21
3  2025-02-18 21:15:00  R K Puram         no    80.8   ppb    21
4  2025-02-18 21:30:00  R K Puram         no    81.6   ppb    21

In [17]:
# -- EDA
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1214664 entries, 0 to 1214663
Data columns (total 6 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   DateTime    1214664 non-null  str
 1   Locations   1214664 non-null  str
 2   Parameters  1214664 non-null  str
 3   Values      1212121 non-null  float64
 4   Units       1214664 non-null  str
 5   hour        1214664 non-null  int64
dtypes: float64(1), int64(1), str(4)
memory usage: 55.6 MB

In [19]:
df.shape

(1214664, 6)

In [21]:
df.isnull().sum() / len(df) * 100

DateTime      0.000000
Locations     0.000000
Parameters    0.000000
Values        0.209358
Units         0.000000
hour          0.000000
dtype: float64

In [22]:
df.head()

              DateTime  Locations Parameters  Values Units  hour
0  2025-02-18 20:00:00  R K Puram         no    93.2   ppb    20
1  2025-02-18 20:15:00  R K Puram         no    90.4   ppb    20
2  2025-02-18 21:00:00  R K Puram         no    84.7   ppb    21
3  2025-02-18 21:15:00  R K Puram         no    80.8   ppb    21
4  2025-02-18 21:30:00  R K Puram         no    81.6   ppb    21

In [24]:
df.dropna(subset=['Values'], inplace=True)
df.isnull().sum()

DateTime      0
Locations     0
Parameters    0
Values        0
Units         0
hour          0
dtype: int64

In [25]:
print(df['DateTime'].dtype)

str

In [27]:
df['DateTime'] = pd.to_datetime(df['DateTime'])

In [28]:
print(df['DateTime'].dtype)

datetime64[us]

In [30]:
# making some date time column for analysyis more information
df['Hour'] = df['DateTime'].dt.hour
df['day_of_week'] = df['DateTime'].dt.day_name()
df['month'] = df['DateTime'].dt.month
df['date'] = df['DateTime'].dt.date

print(df.head())

             DateTime  Locations Parameters  Values Units  hour  Hour  \
0 2025-02-18 20:00:00  R K Puram         no    93.2   ppb    20    20
1 2025-02-18 20:15:00  R K Puram         no    90.4   ppb    20    20
2 2025-02-18 21:00:00  R K Puram         no    84.7   ppb    21    21
3 2025-02-18 21:15:00  R K Puram         no    80.8   ppb    21    21
4 2025-02-18 21:30:00  R K Puram         no    81.6   ppb    21    21

  day_of_week  month        date
0     Tuesday      2  2025-02-18
1     Tuesday      2  2025-02-18
2     Tuesday      2  2025-02-18
3     Tuesday      2  2025-02-18
4     Tuesday      2  2025-02-18

In [31]:
# now we checking duplicates
print("duplicates: ",df.duplicated().sum())

duplicates:  0

In [32]:
print(df.describe())

                         DateTime        Values          hour          Hour  \
count                     1212121  1.212121e+06  1.212121e+06  1.212121e+06
mean   2025-10-06 02:29:25.552844  5.829616e+01  1.127804e+01  1.127804e+01
min           2025-02-18 20:00:00 -9.999000e+03  0.000000e+00  0.000000e+00
25%           2025-06-13 11:30:00  1.880000e+00  5.000000e+00  5.000000e+00
50%           2025-10-06 05:16:00  2.500000e+01  1.100000e+01  1.100000e+01
75%           2026-01-06 14:00:00  7.300000e+01  1.700000e+01  1.700000e+01
max           2026-05-24 18:00:00  5.183500e+03  2.300000e+01  2.300000e+01
std                           NaN  1.410937e+02  6.960476e+00  6.960476e+00

              month
count  1.212121e+06
mean   6.492690e+00
min    1.000000e+00
25%    4.000000e+00
50%    6.000000e+00
75%    1.000000e+01
max    1.200000e+01
std    3.308368e+00

In [ ]:
# now i'm going to do final EDA 
df.head()

,DateTime,Locations,Parameters,Values,Units,hour,Hour,day_of_week,month,date
0,2025-02-18 20:00:00,R K Puram,no,93.2,ppb,20,20,Tuesday,2,2025-02-18
1,2025-02-18 20:15:00,R K Puram,no,90.4,ppb,20,20,Tuesday,2,2025-02-18
2,2025-02-18 21:00:00,R K Puram,no,84.7,ppb,21,21,Tuesday,2,2025-02-18
3,2025-02-18 21:15:00,R K Puram,no,80.8,ppb,21,21,Tuesday,2,2025-02-18
4,2025-02-18 21:30:00,R K Puram,no,81.6,ppb,21,21,Tuesday,2,2025-02-18

In [34]:
print('locations: ',df['Locations'].nunique())
df['Locations'].unique()

locations:  4

<StringArray>
['R K Puram', 'Punjabi Bagh', 'Anand Vihar', 'Pusa']
Length: 4, dtype: str

In [35]:
print('parameters: ',df['Parameters'].nunique())
df['Parameters'].unique()

parameters:  12

<StringArray>
[              'no',               'o3',             'pm25',
              'no2',             'pm10',               'co',
      'temperature', 'relativehumidity',              'so2',
       'wind_speed',   'wind_direction',              'nox']
Length: 12, dtype: str

In [ ]:
# finding date range
print("from:", df['DateTime'].min())111
print("to", df['DateTime'].max())

from: 2025-02-18 20:00:00
to 2026-05-24 18:00:00

In [31]:
# lowering the column names for better handling
df.columns = df.columns.str.lower()

In [49]:
df['hour'] = df['datetime'].dt.hour

In [50]:
# connecting and exporting clean data to sql database(postgresql)
engine = create_engine('postgresql://postgres:1920@localhost:5432/air_quality_db')
df.to_sql('air_quality_data', engine, if_exists='replace', index=False)

print("data loaded successfully to the database.")

data loaded successfully to the database.

In [29]:
# visualization of some sql querry results

sql_result = {
    'parameters' : ['pm10', 'pm25', 'no2', 'o3', 'co'],
    'total_readings': [109141, 107816, 111393, 108859, 109574],
    'exceedences' : [83203, 60030, 13310, 0, 0],
    'exceeding_pct': [76.2, 55.7, 11.9, 0.0, 0.0]
}

df = pd.DataFrame(sql_result)

df.sort_values(by='exceeding_pct', ascending=True)

new_mapping = {
    'pm10' : 'Coarse Particulate Matter (PM10)',
    'pm25' : 'Fine Particulate Matter (PM2.5)',
    'no2' : 'Nitrogen Dioxide (NO2)',
    'o3' : 'Ozone (O3)',
    'co' : 'Carbon Monoxide (CO)'
}

df['pollutant_name'] = df['parameters'].map(new_mapping)

# Initialize the base Plotly Express chart

fig = px.bar(
    df,
    x = 'exceeding_pct',
    y = 'pollutant_name',
    orientation = 'h',
    text = 'exceeding_pct',
    title = '<b>Air Quality Alert: Which Pollutants Frequently Exceed Safe Health Limits?</b>',
    labels = {
        'exceeding_pct' : 'Percentage of unhealthy readings (%)',
        'pollutant_name' : 'Air Pollutant Type'
    },
    template = 'plotly_white'
)

# Polish the visual aesthetics and customize the interactive mouse-hover box
fig.update_traces(
    marker_color = '#e74c3c',
    texttemplate = '%{text}%',
    textposition = 'outside',
    hovertemplate=(
        '<b>%{y}</b><br><br>' +
        '⚠️ Share Unhealthy: <b>%{x}%</b><br>' +
        '📊 Total Readings Logged: %{customdata[0]:,}<br>' +
        '❌ Number of Violations: %{customdata[1]:,}<extra></extra>'
    ),
    customdata = df[['total_readings', 'exceedences']]  
)

# Refine text sizes, constraints, and spacing margins
fig.update_layout(
    title_font_size =20,
    xaxis=dict(
        ticksuffix = '%',
        range = [0, max(df['exceeding_pct'] + 10)]
    ),
    margin=dict(l=220, r=50, t=80, b=50),
    height = 450
)
fig.show();